# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhuQuocTravel_Mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhuQuocTravel_Mobile
  pod 'SnapKit', '~>4.0.0'
  pod "Floaty", "~> 4"

  target 'PhuQuocTravel_MobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhuQuocTravel_MobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
